"""create all 7 tables

Revision ID: bf6c547c896d
Revises: 
Create Date: 2026-07-04 13:40:28.326754

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf6c547c896d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applicants",
        sa.Column("SK_ID_CURR", sa.Integer(), nullable=False),
        sa.Column("TARGET", sa.Integer(), nullable=True),
        sa.Column("NAME_CONTRACT_TYPE", sa.String(), nullable=True),
        sa.Column("CODE_GENDER", sa.String(), nullable=True),
        sa.Column("FLAG_OWN_CAR", sa.String(), nullable=True),
        sa.Column("FLAG_OWN_REALTY", sa.String(), nullable=True),
        sa.Column("CNT_CHILDREN", sa.Integer(), nullable=True),
        sa.Column("AMT_INCOME_TOTAL", sa.Float(), nullable=True),
        sa.Column("AMT_CREDIT", sa.Float(), nullable=True),
        sa.Column("AMT_ANNUITY", sa.Float(), nullable=True),
        sa.Column("AMT_GOODS_PRICE", sa.Float(), nullable=True),
        sa.Column("NAME_TYPE_SUITE", sa.String(), nullable=True),
        sa.Column("NAME_INCOME_TYPE", sa.String(), nullable=True),
        sa.Column("NAME_EDUCATION_TYPE", sa.String(), nullable=True),
        sa.Column("NAME_FAMILY_STATUS", sa.String(), nullable=True),
        sa.Column("NAME_HOUSING_TYPE", sa.String(), nullable=True),
        sa.Column("REGION_POPULATION_RELATIVE", sa.Float(), nullable=True),
        sa.Column("DAYS_BIRTH", sa.Integer(), nullable=True),
        sa.Column("DAYS_EMPLOYED", sa.Integer(), nullable=True),
        sa.Column("DAYS_REGISTRATION", sa.Float(), nullable=True),
        sa.Column("DAYS_ID_PUBLISH", sa.Integer(), nullable=True),
        sa.Column("OWN_CAR_AGE", sa.Float(), nullable=True),
        sa.Column("FLAG_MOBIL", sa.Integer(), nullable=True),
        sa.Column("FLAG_EMP_PHONE", sa.Integer(), nullable=True),
        sa.Column("FLAG_WORK_PHONE", sa.Integer(), nullable=True),
        sa.Column("FLAG_CONT_MOBILE", sa.Integer(), nullable=True),
        sa.Column("FLAG_PHONE", sa.Integer(), nullable=True),
        sa.Column("FLAG_EMAIL", sa.Integer(), nullable=True),
        sa.Column("OCCUPATION_TYPE", sa.String(), nullable=True),
        sa.Column("CNT_FAM_MEMBERS", sa.Float(), nullable=True),
        sa.Column("REGION_RATING_CLIENT", sa.Integer(), nullable=True),
        sa.Column("REGION_RATING_CLIENT_W_CITY", sa.Integer(), nullable=True),
        sa.Column("WEEKDAY_APPR_PROCESS_START", sa.String(), nullable=True),
        sa.Column("HOUR_APPR_PROCESS_START", sa.Integer(), nullable=True),
        sa.Column("REG_REGION_NOT_LIVE_REGION", sa.Integer(), nullable=True),
        sa.Column("REG_REGION_NOT_WORK_REGION", sa.Integer(), nullable=True),
        sa.Column("LIVE_REGION_NOT_WORK_REGION", sa.Integer(), nullable=True),
        sa.Column("REG_CITY_NOT_LIVE_CITY", sa.Integer(), nullable=True),
        sa.Column("REG_CITY_NOT_WORK_CITY", sa.Integer(), nullable=True),
        sa.Column("LIVE_CITY_NOT_WORK_CITY", sa.Integer(), nullable=True),
        sa.Column("ORGANIZATION_TYPE", sa.String(), nullable=True),
        sa.Column("EXT_SOURCE_1", sa.Float(), nullable=True),
        sa.Column("EXT_SOURCE_2", sa.Float(), nullable=True),
        sa.Column("EXT_SOURCE_3", sa.Float(), nullable=True),
        sa.Column("APARTMENTS_AVG", sa.Float(), nullable=True),
        sa.Column("BASEMENTAREA_AVG", sa.Float(), nullable=True),
        sa.Column("YEARS_BEGINEXPLUATATION_AVG", sa.Float(), nullable=True),
        sa.Column("YEARS_BUILD_AVG", sa.Float(), nullable=True),
        sa.Column("COMMONAREA_AVG", sa.Float(), nullable=True),
        sa.Column("ELEVATORS_AVG", sa.Float(), nullable=True),
        sa.Column("ENTRANCES_AVG", sa.Float(), nullable=True),
        sa.Column("FLOORSMAX_AVG", sa.Float(), nullable=True),
        sa.Column("FLOORSMIN_AVG", sa.Float(), nullable=True),
        sa.Column("LANDAREA_AVG", sa.Float(), nullable=True),
        sa.Column("LIVINGAPARTMENTS_AVG", sa.Float(), nullable=True),
        sa.Column("LIVINGAREA_AVG", sa.Float(), nullable=True),
        sa.Column("NONLIVINGAPARTMENTS_AVG", sa.Float(), nullable=True),
        sa.Column("NONLIVINGAREA_AVG", sa.Float(), nullable=True),
        sa.Column("APARTMENTS_MODE", sa.Float(), nullable=True),
        sa.Column("BASEMENTAREA_MODE", sa.Float(), nullable=True),
        sa.Column("YEARS_BEGINEXPLUATATION_MODE", sa.Float(), nullable=True),
        sa.Column("YEARS_BUILD_MODE", sa.Float(), nullable=True),
        sa.Column("COMMONAREA_MODE", sa.Float(), nullable=True),
        sa.Column("ELEVATORS_MODE", sa.Float(), nullable=True),
        sa.Column("ENTRANCES_MODE", sa.Float(), nullable=True),
        sa.Column("FLOORSMAX_MODE", sa.Float(), nullable=True),
        sa.Column("FLOORSMIN_MODE", sa.Float(), nullable=True),
        sa.Column("LANDAREA_MODE", sa.Float(), nullable=True),
        sa.Column("LIVINGAPARTMENTS_MODE", sa.Float(), nullable=True),
        sa.Column("LIVINGAREA_MODE", sa.Float(), nullable=True),
        sa.Column("NONLIVINGAPARTMENTS_MODE", sa.Float(), nullable=True),
        sa.Column("NONLIVINGAREA_MODE", sa.Float(), nullable=True),
        sa.Column("APARTMENTS_MEDI", sa.Float(), nullable=True),
        sa.Column("BASEMENTAREA_MEDI", sa.Float(), nullable=True),
        sa.Column("YEARS_BEGINEXPLUATATION_MEDI", sa.Float(), nullable=True),
        sa.Column("YEARS_BUILD_MEDI", sa.Float(), nullable=True),
        sa.Column("COMMONAREA_MEDI", sa.Float(), nullable=True),
        sa.Column("ELEVATORS_MEDI", sa.Float(), nullable=True),
        sa.Column("ENTRANCES_MEDI", sa.Float(), nullable=True),
        sa.Column("FLOORSMAX_MEDI", sa.Float(), nullable=True),
        sa.Column("FLOORSMIN_MEDI", sa.Float(), nullable=True),
        sa.Column("LANDAREA_MEDI", sa.Float(), nullable=True),
        sa.Column("LIVINGAPARTMENTS_MEDI", sa.Float(), nullable=True),
        sa.Column("LIVINGAREA_MEDI", sa.Float(), nullable=True),
        sa.Column("NONLIVINGAPARTMENTS_MEDI", sa.Float(), nullable=True),
        sa.Column("NONLIVINGAREA_MEDI", sa.Float(), nullable=True),
        sa.Column("FONDKAPREMONT_MODE", sa.String(), nullable=True),
        sa.Column("HOUSETYPE_MODE", sa.String(), nullable=True),
        sa.Column("TOTALAREA_MODE", sa.Float(), nullable=True),
        sa.Column("WALLSMATERIAL_MODE", sa.String(), nullable=True),
        sa.Column("EMERGENCYSTATE_MODE", sa.String(), nullable=True),
        sa.Column("OBS_30_CNT_SOCIAL_CIRCLE", sa.Float(), nullable=True),
        sa.Column("DEF_30_CNT_SOCIAL_CIRCLE", sa.Float(), nullable=True),
        sa.Column("OBS_60_CNT_SOCIAL_CIRCLE", sa.Float(), nullable=True),
        sa.Column("DEF_60_CNT_SOCIAL_CIRCLE", sa.Float(), nullable=True),
        sa.Column("DAYS_LAST_PHONE_CHANGE", sa.Float(), nullable=True),
        sa.Column("FLAG_DOCUMENT_2", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_3", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_4", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_5", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_6", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_7", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_8", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_9", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_10", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_11", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_12", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_13", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_14", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_15", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_16", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_17", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_18", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_19", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_20", sa.Integer(), nullable=True),
        sa.Column("FLAG_DOCUMENT_21", sa.Integer(), nullable=True),
        sa.Column("AMT_REQ_CREDIT_BUREAU_HOUR", sa.Float(), nullable=True),
        sa.Column("AMT_REQ_CREDIT_BUREAU_DAY", sa.Float(), nullable=True),
        sa.Column("AMT_REQ_CREDIT_BUREAU_WEEK", sa.Float(), nullable=True),
        sa.Column("AMT_REQ_CREDIT_BUREAU_MON", sa.Float(), nullable=True),
        sa.Column("AMT_REQ_CREDIT_BUREAU_QRT", sa.Float(), nullable=True),
        sa.Column("AMT_REQ_CREDIT_BUREAU_YEAR", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("SK_ID_CURR"),
    )
    op.create_index(
        op.f("ix_applicants_SK_ID_CURR"), "applicants", ["SK_ID_CURR"], unique=False
    )
    op.create_table(
        "bureau",
        sa.Column("SK_ID_BUREAU", sa.Integer(), nullable=False),
        sa.Column("SK_ID_CURR", sa.Integer(), nullable=True),
        sa.Column("CREDIT_ACTIVE", sa.String(), nullable=True),
        sa.Column("CREDIT_CURRENCY", sa.String(), nullable=True),
        sa.Column("DAYS_CREDIT", sa.Integer(), nullable=True),
        sa.Column("CREDIT_DAY_OVERDUE", sa.Integer(), nullable=True),
        sa.Column("DAYS_CREDIT_ENDDATE", sa.Float(), nullable=True),
        sa.Column("DAYS_ENDDATE_FACT", sa.Float(), nullable=True),
        sa.Column("AMT_CREDIT_MAX_OVERDUE", sa.Float(), nullable=True),
        sa.Column("CNT_CREDIT_PROLONG", sa.Integer(), nullable=True),
        sa.Column("AMT_CREDIT_SUM", sa.Float(), nullable=True),
        sa.Column("AMT_CREDIT_SUM_DEBT", sa.Float(), nullable=True),
        sa.Column("AMT_CREDIT_SUM_LIMIT", sa.Float(), nullable=True),
        sa.Column("AMT_CREDIT_SUM_OVERDUE", sa.Float(), nullable=True),
        sa.Column("CREDIT_TYPE", sa.String(), nullable=True),
        sa.Column("DAYS_CREDIT_UPDATE", sa.Integer(), nullable=True),
        sa.Column("AMT_ANNUITY", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("SK_ID_BUREAU"),
    )
    op.create_index(
        op.f("ix_bureau_SK_ID_BUREAU"), "bureau", ["SK_ID_BUREAU"], unique=False
    )
    op.create_index(
        op.f("ix_bureau_SK_ID_CURR"), "bureau", ["SK_ID_CURR"], unique=False
    )
    op.create_table(
        "bureau_balance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("SK_ID_BUREAU", sa.Integer(), nullable=True),
        sa.Column("MONTHS_BALANCE", sa.Integer(), nullable=True),
        sa.Column("STATUS", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bureau_balance_SK_ID_BUREAU"),
        "bureau_balance",
        ["SK_ID_BUREAU"],
        unique=False,
    )
    op.create_table(
        "credit_card_balance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("SK_ID_PREV", sa.Integer(), nullable=True),
        sa.Column("SK_ID_CURR", sa.Integer(), nullable=True),
        sa.Column("MONTHS_BALANCE", sa.Integer(), nullable=True),
        sa.Column("AMT_BALANCE", sa.Float(), nullable=True),
        sa.Column("AMT_CREDIT_LIMIT_ACTUAL", sa.Integer(), nullable=True),
        sa.Column("AMT_DRAWINGS_ATM_CURRENT", sa.Float(), nullable=True),
        sa.Column("AMT_DRAWINGS_CURRENT", sa.Float(), nullable=True),
        sa.Column("AMT_DRAWINGS_OTHER_CURRENT", sa.Float(), nullable=True),
        sa.Column("AMT_DRAWINGS_POS_CURRENT", sa.Float(), nullable=True),
        sa.Column("AMT_INST_MIN_REGULARITY", sa.Float(), nullable=True),
        sa.Column("AMT_PAYMENT_CURRENT", sa.Float(), nullable=True),
        sa.Column("AMT_PAYMENT_TOTAL_CURRENT", sa.Float(), nullable=True),
        sa.Column("AMT_RECEIVABLE_PRINCIPAL", sa.Float(), nullable=True),
        sa.Column("AMT_RECIVABLE", sa.Float(), nullable=True),
        sa.Column("AMT_TOTAL_RECEIVABLE", sa.Float(), nullable=True),
        sa.Column("CNT_DRAWINGS_ATM_CURRENT", sa.Float(), nullable=True),
        sa.Column("CNT_DRAWINGS_CURRENT", sa.Integer(), nullable=True),
        sa.Column("CNT_DRAWINGS_OTHER_CURRENT", sa.Float(), nullable=True),
        sa.Column("CNT_DRAWINGS_POS_CURRENT", sa.Float(), nullable=True),
        sa.Column("CNT_INSTALMENT_MATURE_CUM", sa.Float(), nullable=True),
        sa.Column("NAME_CONTRACT_STATUS", sa.String(), nullable=True),
        sa.Column("SK_DPD", sa.Integer(), nullable=True),
        sa.Column("SK_DPD_DEF", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_card_balance_SK_ID_CURR"),
        "credit_card_balance",
        ["SK_ID_CURR"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_card_balance_SK_ID_PREV"),
        "credit_card_balance",
        ["SK_ID_PREV"],
        unique=False,
    )
    op.create_table(
        "installments_payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("SK_ID_PREV", sa.Integer(), nullable=True),
        sa.Column("SK_ID_CURR", sa.Integer(), nullable=True),
        sa.Column("NUM_INSTALMENT_VERSION", sa.Float(), nullable=True),
        sa.Column("NUM_INSTALMENT_NUMBER", sa.Integer(), nullable=True),
        sa.Column("DAYS_INSTALMENT", sa.Float(), nullable=True),
        sa.Column("DAYS_ENTRY_PAYMENT", sa.Float(), nullable=True),
        sa.Column("AMT_INSTALMENT", sa.Float(), nullable=True),
        sa.Column("AMT_PAYMENT", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_installments_payments_SK_ID_CURR"),
        "installments_payments",
        ["SK_ID_CURR"],
        unique=False,
    )
    op.create_index(
        op.f("ix_installments_payments_SK_ID_PREV"),
        "installments_payments",
        ["SK_ID_PREV"],
        unique=False,
    )
    op.create_table(
        "pos_cash_balance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("SK_ID_PREV", sa.Integer(), nullable=True),
        sa.Column("SK_ID_CURR", sa.Integer(), nullable=True),
        sa.Column("MONTHS_BALANCE", sa.Integer(), nullable=True),
        sa.Column("CNT_INSTALMENT", sa.Float(), nullable=True),
        sa.Column("CNT_INSTALMENT_FUTURE", sa.Float(), nullable=True),
        sa.Column("NAME_CONTRACT_STATUS", sa.String(), nullable=True),
        sa.Column("SK_DPD", sa.Integer(), nullable=True),
        sa.Column("SK_DPD_DEF", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pos_cash_balance_SK_ID_CURR"),
        "pos_cash_balance",
        ["SK_ID_CURR"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pos_cash_balance_SK_ID_PREV"),
        "pos_cash_balance",
        ["SK_ID_PREV"],
        unique=False,
    )
    op.create_table(
        "previous_application",
        sa.Column("SK_ID_PREV", sa.Integer(), nullable=False),
        sa.Column("SK_ID_CURR", sa.Integer(), nullable=True),
        sa.Column("NAME_CONTRACT_TYPE", sa.String(), nullable=True),
        sa.Column("AMT_ANNUITY", sa.Float(), nullable=True),
        sa.Column("AMT_APPLICATION", sa.Float(), nullable=True),
        sa.Column("AMT_CREDIT", sa.Float(), nullable=True),
        sa.Column("AMT_DOWN_PAYMENT", sa.Float(), nullable=True),
        sa.Column("AMT_GOODS_PRICE", sa.Float(), nullable=True),
        sa.Column("WEEKDAY_APPR_PROCESS_START", sa.String(), nullable=True),
        sa.Column("HOUR_APPR_PROCESS_START", sa.Integer(), nullable=True),
        sa.Column("FLAG_LAST_APPL_PER_CONTRACT", sa.String(), nullable=True),
        sa.Column("NFLAG_LAST_APPL_IN_DAY", sa.Integer(), nullable=True),
        sa.Column("RATE_DOWN_PAYMENT", sa.Float(), nullable=True),
        sa.Column("RATE_INTEREST_PRIMARY", sa.Float(), nullable=True),
        sa.Column("RATE_INTEREST_PRIVILEGED", sa.Float(), nullable=True),
        sa.Column("NAME_CASH_LOAN_PURPOSE", sa.String(), nullable=True),
        sa.Column("NAME_CONTRACT_STATUS", sa.String(), nullable=True),
        sa.Column("DAYS_DECISION", sa.Integer(), nullable=True),
        sa.Column("NAME_PAYMENT_TYPE", sa.String(), nullable=True),
        sa.Column("CODE_REJECT_REASON", sa.String(), nullable=True),
        sa.Column("NAME_TYPE_SUITE", sa.String(), nullable=True),
        sa.Column("NAME_CLIENT_TYPE", sa.String(), nullable=True),
        sa.Column("NAME_GOODS_CATEGORY", sa.String(), nullable=True),
        sa.Column("NAME_PORTFOLIO", sa.String(), nullable=True),
        sa.Column("NAME_PRODUCT_TYPE", sa.String(), nullable=True),
        sa.Column("CHANNEL_TYPE", sa.String(), nullable=True),
        sa.Column("SELLERPLACE_AREA", sa.Integer(), nullable=True),
        sa.Column("NAME_SELLER_INDUSTRY", sa.String(), nullable=True),
        sa.Column("CNT_PAYMENT", sa.Float(), nullable=True),
        sa.Column("NAME_YIELD_GROUP", sa.String(), nullable=True),
        sa.Column("PRODUCT_COMBINATION", sa.String(), nullable=True),
        sa.Column("DAYS_FIRST_DRAWING", sa.Float(), nullable=True),
        sa.Column("DAYS_FIRST_DUE", sa.Float(), nullable=True),
        sa.Column("DAYS_LAST_DUE_1ST_VERSION", sa.Float(), nullable=True),
        sa.Column("DAYS_LAST_DUE", sa.Float(), nullable=True),
        sa.Column("DAYS_TERMINATION", sa.Float(), nullable=True),
        sa.Column("NFLAG_INSURED_ON_APPROVAL", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("SK_ID_PREV"),
    )
    op.create_index(
        op.f("ix_previous_application_SK_ID_CURR"),
        "previous_application",
        ["SK_ID_CURR"],
        unique=False,
    )
    op.create_index(
        op.f("ix_previous_application_SK_ID_PREV"),
        "previous_application",
        ["SK_ID_PREV"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_previous_application_SK_ID_PREV"), table_name="previous_application"
    )
    op.drop_index(
        op.f("ix_previous_application_SK_ID_CURR"), table_name="previous_application"
    )
    op.drop_table("previous_application")
    op.drop_index(op.f("ix_pos_cash_balance_SK_ID_PREV"), table_name="pos_cash_balance")
    op.drop_index(op.f("ix_pos_cash_balance_SK_ID_CURR"), table_name="pos_cash_balance")
    op.drop_table("pos_cash_balance")
    op.drop_index(
        op.f("ix_installments_payments_SK_ID_PREV"), table_name="installments_payments"
    )
    op.drop_index(
        op.f("ix_installments_payments_SK_ID_CURR"), table_name="installments_payments"
    )
    op.drop_table("installments_payments")
    op.drop_index(
        op.f("ix_credit_card_balance_SK_ID_PREV"), table_name="credit_card_balance"
    )
    op.drop_index(
        op.f("ix_credit_card_balance_SK_ID_CURR"), table_name="credit_card_balance"
    )
    op.drop_table("credit_card_balance")
    op.drop_index(op.f("ix_bureau_balance_SK_ID_BUREAU"), table_name="bureau_balance")
    op.drop_table("bureau_balance")
    op.drop_index(op.f("ix_bureau_SK_ID_CURR"), table_name="bureau")
    op.drop_index(op.f("ix_bureau_SK_ID_BUREAU"), table_name="bureau")
    op.drop_table("bureau")
    op.drop_index(op.f("ix_applicants_SK_ID_CURR"), table_name="applicants")
    op.drop_table("applicants")
    # ### end Alembic commands ###
