from sqlalchemy import Column, Float, Integer, String

from app.db.database import Base


class PreviousApplication(Base):
    __tablename__ = "previous_application"

    SK_ID_PREV = Column(Integer, primary_key=True, index=True)
    SK_ID_CURR = Column(Integer, index=True)
    NAME_CONTRACT_TYPE = Column(String)
    AMT_ANNUITY = Column(Float)
    AMT_APPLICATION = Column(Float)
    AMT_CREDIT = Column(Float)
    AMT_DOWN_PAYMENT = Column(Float)
    AMT_GOODS_PRICE = Column(Float)
    WEEKDAY_APPR_PROCESS_START = Column(String)
    HOUR_APPR_PROCESS_START = Column(Integer)
    FLAG_LAST_APPL_PER_CONTRACT = Column(String)
    NFLAG_LAST_APPL_IN_DAY = Column(Integer)
    RATE_DOWN_PAYMENT = Column(Float)
    RATE_INTEREST_PRIMARY = Column(Float)
    RATE_INTEREST_PRIVILEGED = Column(Float)
    NAME_CASH_LOAN_PURPOSE = Column(String)
    NAME_CONTRACT_STATUS = Column(String)
    DAYS_DECISION = Column(Integer)
    NAME_PAYMENT_TYPE = Column(String)
    CODE_REJECT_REASON = Column(String)
    NAME_TYPE_SUITE = Column(String)
    NAME_CLIENT_TYPE = Column(String)
    NAME_GOODS_CATEGORY = Column(String)
    NAME_PORTFOLIO = Column(String)
    NAME_PRODUCT_TYPE = Column(String)
    CHANNEL_TYPE = Column(String)
    SELLERPLACE_AREA = Column(Integer)
    NAME_SELLER_INDUSTRY = Column(String)
    CNT_PAYMENT = Column(Float)
    NAME_YIELD_GROUP = Column(String)
    PRODUCT_COMBINATION = Column(String)
    DAYS_FIRST_DRAWING = Column(Float)
    DAYS_FIRST_DUE = Column(Float)
    DAYS_LAST_DUE_1ST_VERSION = Column(Float)
    DAYS_LAST_DUE = Column(Float)
    DAYS_TERMINATION = Column(Float)
    NFLAG_INSURED_ON_APPROVAL = Column(Float)
